[package]
name = "learn-vocab"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = {version = "3.0.14", features=["cargo"]}
rusqlite = {version = "0.26.3", features=["bundled"]}
